### PR TITLE
Use poetry

### PR DESCRIPTION
**Pull request by adria0**
[Poetry](https://python-poetry.org/) is a modern build system for python _ala_ cargo or npm, it creates automatically the environment execution and it's really easy to use, is in active development in github.

_Note_: I'm not an python expert, and I did not deep researched about other possible build systems.

WDYT?

### CODE REVIEW

**Comment by adria0** [comment]
@ChihChengLiang, the change originally came from the fact that I had linker problems with my M1 (`OSError: Cannot load native module 'Crypto.Hash._keccak': Not found '_keccak.cpython-39-darwin.so'`) when running `make test`.

I've been using poetry because it is really nice and everything goes smooth in M1, so I supposed that this will be a nice improvement for everybody.

**Comment by ChihChengLiang** [comment]
The error message of your issue seems to belong to `pycryptodome`, and in this PR you upgraded the package from 3.11.0 to 3.14.1. It's hard to determine if your issue is resolved by the upgrade of pycryptodome or the introduction of poetry.
Would upgrading pycryptodome solve your issue?
Changing the build system at this stage requires existing collaborators to change their workflow, which I'm inclined not to do so.

**Comment by CPerezz** [comment]
Which change in the workflow does this imply exactly @ChihChengLiang ??

I mean, we can keep the same Makefile masking the internals of using poetry anyway no?

**Comment by adria0** [comment]
@ChihChengLiang, yes if I update the cryptodome it works. I will do another PR just changing this, if this change it too much at this moment 👍

**Comment by adria0** [comment]
Superseded by 173

**Pull request closed without merging**
